### ISSUE TITLE
New ParticleSystem RoadMap

### ISSUE THREAD

**Issue by SantyWang** [cocos/cocos-engine#14749]
### Key Features
* All particle modules are pluggable
* All particle data are pluggable
* Event Generator And Event Receiver (Known as SubEmitter)
* Multiply Renderer (One particle system can includes multiple renderer)
* Particle Expression
* Emitter cascade operation(set LifeCycle, play, stop, pause etc)

### Emitter
* Duration
* LoopMode(includes Once, Multiply, Infinite)
* DelayMode(includes None, FirstLoop, EveryLoop)
* Prewarm
* SimulationSpace (includes World, Local)
* SimulationSpeed
* maxDeltaTime
* CapacityMode (How to react when particle number increased. includes Auto, Fixed)
* PlayOnAwake
* useAutoRandSeed(Using a fixed seed or random seed)
* BoundsMode(How to calculate emitter bounds, includes Auto, Fixed)
* CullingMode(How to react when emitter being culled by frustum culling. includes Always Simulate, Pause, PauseAndCatchUp, StopEmitting, ClearAndFinish)
* FinishAction(How to react when all particles died and emitter is inactive. includes None, Destroy, Disable)

#### Float Expression
* Local Value (like legacy curve range's Constant Mode)
* Float From Curve (like legacy curve range's Curve mode)
* Random Ranged(combine Random Ranged and Constant will produce TwoConstant effect, combine Random Ranged and Float From Curve will produce TwoCurves effect)

#### Vec3 Expression
* 3 Float

#### Color Expression
* Local Value (like legacy gradient range's Color Mode)
* Color from Gradient (like legacy gradient range's Gradient Mode)
* RandomRanged (Combin RandomRanged and Color will produce TwoColor Mode, Combine RandomRanged and Gradient will produce TwoGradient Mode)
* RandomColorFromGrandient (like legacy gradient range's Random Mode)

### Emitter Update
* SpawnRate Module(Legacy named EmitOverTime)
* Burst Module
* SpawnPerUnit Module(Legacy named EmitOverDistance)

### Particle Spawn
* BoxShape Module
* CircleShape Module
* ConeShape Module
* Donut Shape Module
* Grid Shape Module
* Line Shape Module
* HemisphereShape Module
* Rectangle Shape Module
* SphereShape Module

### Particle Update
* Death event generator Module (Generate a death event when particle died)
* Location Event Generator Module (Generate a location event perframe per particle)
* Drag Module (Add a drag according to particle's velocity)
* Inherit Velocity Module (Inherit Emitter's Velocity)
* Solve Module(Solve Force And Velocity)
* State Module (Update Particle's Age, and kill particle when its lifetime elapsed if you want.)
* SubUVAnimation Module(Legacy named Texture Animation Module)
* Rotation Module
* Curl Noise Module (Curl Noise with quality, remap options)
* Limit Velocity Module
* Gravity Module
* Force Module

### Common(Support using in both Particle Spawn and Particle Update)
* AddSpeedInInitialDirection Module (Add speed in particle's initial direction)
* AddVelocity Module
* SetLifeTime Module
* SetColor Module
* SetRotation Module
* SetSize Module
* Multiply Size Module
* Multiply Color Module
* Multiply Color by Speed Module
* Scale Size by Speed Module
* Scale Speed Module
* Sprite Face And Alignment

### Renderer
* Ribbon Renderer Module (Connect particle's position to generate a ribbon)
* Sprite Renderer Module
* Mesh Renderer Module

### Key Features
* Support using in UI
* Custom Parameters (includes UserParameters, EmitterParameters, ParticleParameters)
* Renderer support binding Parameter(For example. Bind Custom Particle Parameter to Renderer.Position)

### Expression
* Binding Parameter (Bind Particle Paramters, Emitter Parameters, UserParameters as expression input)

#### Float Expression
* From Int
* Decompose From Vec3
* Normalized
* Add
* Sub
* Multiply
* Devide
* Sin
* Cos
* Operation If (take a bool expression as condition and do a operation when condition is true)

#### Vec3 Expression
* Normalized
* Make Vec3 from one float
* Add
* Sub
* Multiply
* Devide
* Sin
* Cos
* Operation If (take a bool expression as condition and do a operation when condition is true)

#### Bool Expression
* From Int

#### Int Expression
* From Float

#### Color Expression
* From RGB And Alpha

### Particle Spawn
* Mesh Shape Module
* Skinned Mesh Renderer Shape Module
* Spline Shape(Bezier Curve Based) Module

### Particle Update
* Vortex Velocity Module
* Point Attraction Force Module
* Collision Module
* ForceField Module
* Wind Force Module
* Trigger Module

### Common (Can used in both Particle Spawn and Particle Update)
* Set Parameter Module(Set Any Parameter with Expression)

### Renderer
* Light Renderer Module(Using particle's position to generate light)

## 1.2 
* Compute Shader Based Simulation
* C++ fullly implement,

### Particle Spawn
* Sample Texture (Set Particle's Color from Sampling Texture)
* Kill Particles When Alpha Less Than (Kill Particle according to particle's color alpha chanel)

**Comment by SantyWang** [comment]
Current remaining issues：
- [ ] Scaling Mode (include Hierarchy, Local, Shape)
- [ ] Since the multiple renderer structure, we should split 'Size' and 'Rotation' between Mesh and Sprite.
- [ ] The Alignment.
- [ ] Since the multiple renderer structure,  'SubUVAnimation' module should support operating specific renderer's frameIndex.
- [ ] Since the multiple renderer structure,  some module like 'Curl Noise', 'Drag' can not read or write the common size. So we should introduce some physics factor like 'Mass'.
- [ ] Since 'Size' and 'Rotation' is unnecessary for 'Ribbon Renderer', we should introduce 'Ribbon Width', 'Scale Ribbon Width' modules.
- [ ] Gizmos supporting for all shape modules.
- [ ] Inspector supporting for Stages, Modules and Expressions.
- [ ] Migration from old project.
- [ ] Shader library.
- [ ] SubEmitter spawnRate
- [ ] How to set sub uv tiles for different renderer. 
- [ ] Split ribbon from sub emitter
- [ ] Unit(cm or m)

It seems to need more time to refine the new particle system, so do we need to make some performance optimizations to the existing particles in the near future to gain more time?

**Comment by mikecoker** [comment]
Hi, Panda said I could drop some feedback here.  I'm glad you guys are making improvements to your particle system and I was talking with our VFX guy to see if he had feedback. There were a couple of pieces of functionality we were hoping we could get while you're doing this.  These are features he uses often in Unity

1) Add orbital velocity to the velocity animator. 
2) Add the ability to orient a particle to the velocity
3) Ability to override the Random Number seed with a fixed value.

Thanks,
Mike

**Comment by SantyWang** [comment]
Thanks for feed back. All these features already be planned in the roadmap.

* Orbital Velocity will be a standalong module, and named Vertox Velocity Module. will implemented in v1.1.
* We will implement a module which can adjust particle's face direction and alignment direction.  Named Sprite Face And Alignment Module.
* Yeah, it's a basic requirement. will be implemented in v1.0.

**Comment by whaqzhzd** [comment]
will this feature continue to be developed? It seems to me that it has been stalled for a long time
